### ISSUE TITLE
Error: not an object

### ISSUE THREAD

**Issue by ZanderBrown** [rustwasm/rust-parcel-template#32]
### Describe the Bug

It don't work, see logs

### Steps to Reproduce

1. `npm run start`

### Expected Behavior

The unmodified template to work

### Actual Behavior

**Firefox 67.0.4**
```
TypeError: import object field './rust_parcel.js' is not an Object
```

**Chrome 75.0.3770.100**
```
Uncaught (in promise) TypeError: WebAssembly.instantiate(): Import #0 module="./rust_parcel.js" error: module is not an object or function
  Promise.then (async)
  parcelRequire.0 @ wasm-loader.js:261
  newRequire @ js.00a46daa.js:47
  (anonymous) @ js.00a46daa.js:81
  (anonymous) @ js.00a46daa.js:120
```
### Additional Context

```
$ parcel --version
1.12.3
$ cargo --version
cargo 1.35.0 (6f3e9c367 2019-04-04)
$ rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
$ npm --version
6.9.0
$ node --version
v10.16.0
```

I was trying to get my own project to work and was hitting the same problem, decided to try a "known-good" project and found it happens here as well

No idea what part of the stack broke, can't seem to find any issues about this anywhere

**Comment by espnicholas** [comment]
Same issue on Mac OSX v10.14.4 - Chrome v75.

**Comment by liamcurry** [comment]
Same issue on Windows 10, Firefox 67

**Comment by sendilkumarn** [comment]
it is coming from the plugin used. I will check what can be done here.

**Comment by catsigma** [comment]
I just updated the fix.
This issue should be solved with `parcel-plugin-wasm.rs` @ version `1.2.11`.

**Comment by ZanderBrown** [comment]
Works for me :-)
