### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by sri-rad** [rustwasm/rust-parcel-template#52]
I cloned this package and ran the test server successfully. 

Without changing anything, I ran the build script and the built files were available in `dist/` folder. When I served the contents of the folder and opened it with Chrome, I got the following error in the console.

`Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.`
 
Is there anything that I am missing?

**Comment by Lxrd-AJ** [comment]
This is most likely because the server you're running doesn't know about `.wasm` files. 

* You can either modify your server to handle `.wasm` files 
* or simply just use a server that knows how to handle them. I ended up using `https://crates.io/crates/https`

**Comment by xtuc** [comment]
@Lxrd-AJ is correct. The .wasm file is served with an incorrect mime type, due to HTTP server configuration.
